[package]
name = "rlp"
version = "0.4.0"
description = "Recursive-length prefix encoding, decoding, and compression"
repository = "https://github.com/paritytech/parity-common"
license = "MIT/Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = "1.0"
rustc-hex = {version = "2.0", default-features = false }

[dev-dependencies]
hex-literal = "0.1"
